# Generated by Django 2.2.7 on 2019-11-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags_manager', '0002_auto_20191125_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tag_id',
        ),
    ]
