# Generated by Django 2.2.7 on 2019-11-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors_manager', '0002_authorusership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorusership',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='authorusership',
            old_name='user_id',
            new_name='user',
        ),
    ]
