# Generated by Django 2.2.7 on 2019-11-25 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags_manager', '0001_initial'),
        ('authors_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=35)),
                ('post_slug', models.SlugField(max_length=40)),
                ('post_image', models.ImageField(default='assets/img/bitmap/no_image.png', upload_to='assets/post_content/images/thumbnails/')),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts_manager.Post')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags_manager.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors_manager.Author')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts_manager.Post')),
            ],
        ),
    ]
