# Generated by Django 2.2.7 on 2019-11-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags_manager', '0001_initial'),
        ('authors_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=35)),
                ('post_slug', models.SlugField(max_length=40)),
                ('post_image', models.ImageField(default='assets/img/bitmap/no_image.png', upload_to='assets/post_content/images/thumbnails/')),
                ('post_content', models.TextField()),
                ('date_add', models.DateField(auto_now_add=True)),
                ('authors', models.ManyToManyField(to='authors_manager.Author')),
                ('tags', models.ManyToManyField(to='tags_manager.Tag')),
            ],
        ),
    ]
