# Generated by Django 2.2.7 on 2019-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_excerpt',
            field=models.CharField(default='aaa', max_length=300),
            preserve_default=False,
        ),
    ]
