# Generated by Django 2.2.7 on 2019-11-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorship',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='authorship',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='tagship',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='tagship',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='tagship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags_manager.Tag', to_field='tag_id'),
        ),
    ]
