# Generated by Django 2.2.7 on 2019-11-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts_manager', '0002_auto_20191125_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags_manager.Tag', to_field='tag'),
        ),
    ]
